version: '3.9'

services:
  sports-api-app-container:
    container_name: sports-api-app-container
    build:
      dockerfile: Dockerfile
    image: sports-api-app-image:latest
    ports:
      - "8080:8080"
    networks:
      - spring-cloud-network
    depends_on:
      - sports-api-db-container

  sports-api-db-container:
    image: postgres:14-alpine
    container_name: sports-api-db-container
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=sports_api_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - spring-cloud-network

volumes:
  data:

networks:
  spring-cloud-network:
    driver: bridge
