spring:
  application:
    name: sports-api

  datasource:
    url: jdbc:postgresql://localhost:5432/sports_api_db
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080
